### ISSUE TITLE
How to limit number of cpu used by the script

### ISSUE THREAD

**Issue by Ziaeemehr** [SwissDataScienceCenter/DeepSphere#32]
Hi,
It's a blind question. One of our cluster members use your package and messed up other's job, because she can not control the number of cpu that her script use. 
Do you know how  can she fix this, 
I don't know more details about the script.
and thanks in advance for any guide.

**Comment by nperraud** [comment]
Hello,

The paralellization is entirely done by tensorflow. So the solution is to limit the access to ressources to tensorflow. Probably something like this:
https://stackoverflow.com/questions/38615121/limit-tensorflow-cpu-and-memory-usage#38619385
I have not tried.

By the way, I recommend using a GPU instead of CPU.

Good luck
